### ISSUE TITLE
Articles with apostrophes

### ISSUE THREAD

**Issue by fgoudreault** [Jinwen-XU/crefthe#3]
Is there a way to use articles with apostrophes? For instance, in French, I tried using

```
  \crefthename{equation}[l']{équation}[les]{équations}
```

in order to use `\crefthe` with an equation. However, this inserts a space between `l'` and `équation` givint `l' équation`while I'd like `l'équation`. Is there a way to remove it?

**Comment by Jinwen-XU** [comment]
Care has been taken for articles with apostrophes, so in principle there should be no problem. Would you mind providing an example that gives you the wrong output? I cannot seem to reproduce your issue:

```
\documentclass{article}
\usepackage[french]{babel}
\usepackage{crefthe}
\crefthename{equation}[l']{équation}[les]{équations}
\begin{document}
\begin{equation}\label{eq:alpha}
    \alpha
\end{equation}
\crefthe[de]{eq:alpha}
\end{document}
```
gives the correct result:

<img width="613" alt="image" src="https://github.com/Jinwen-XU/crefthe/assets/80377812/30599f8b-fad0-4c6e-ad0c-5bb55f2739c8">

**Comment by fgoudreault** [comment]
Thanks @Jinwen-XU for the quick reply! Perhaps I should've stated this from the start but I am using Overleaf if that's relevent. For some reason, on Overleaf, your MWE does not work: there is a space between "l'" and the word "équation". No warnings are issued so not sure why this happens. Do you have any idea why?

![image](https://github.com/Jinwen-XU/crefthe/assets/12396317/1a38312d-fe52-4d89-80f5-c2960abfa3ae)

**Comment by Jinwen-XU** [comment]
Perhaps you are using an old version of this package (the latest fix to this issue was introduced in Update 2023-10-21, f0176d0bd30562196cdc3799e99dcc607b531030), but without further information I cannot really tell. It would be nice if you could provide the content of the `.log` file. Meanwhile, try placing the newest [`crefthe.sty`](https://github.com/Jinwen-XU/crefthe/blob/main/crefthe.sty) in your working folder and see if this solves the problem.

**Comment by fgoudreault** [comment]
ah yes indeed Overleaf seems to use an older version. By placing the latest sty file the issue is solved. Thanks
